### ISSUE TITLE
Client: FileNotFoundError: [Errno 2] No such file or directory: 'IP.txt'

### ISSUE THREAD

**Issue by sjuk** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#45]
Client failed to start after a fresh `git clone https://github.com/Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi`.

Expected: Client starts.

Instead: Client failed to start.

Output: ("LANG=C" is to force English language. The result is the same without, only in German language.)

```
~/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/Code/Client$ LANG=C python Main.py 
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
Traceback (most recent call last):
  File "/home/sjuk/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/Code/Client/Main.py", line 823, in <module>
    myshow=mywindow()
  File "/home/sjuk/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/Code/Client/Main.py", line 29, in __init__
    file = open('IP.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'IP.txt'
```

Root cause: There is a file called '**ip**.txt' instead of '**IP**.txt'. Note that linux is case sensitive.

Workaround: Rename ip.txt file to IP.txt without changing code.

Solution: Change code handling the case of missing text file.
- Start with a default value (without the file).
- Create a default file with the right name.
- Make search for the file case insensitive.

**Comment by fire-eggs** [comment]
Better yet, add exception handling in Main.py, lines 29-31:
```python
        file = open('IP.txt', 'r')
        self.IP.setText(str(file.readline()))
        file.close()
```
to:
```python
        try:
            file = open('IP.txt', 'r')
            self.IP.setText(str(file.readline()))
            file.close()
        except:
            pass
```
